project:
  type: website
  output-dir: docs

website:
  title: "Геоинформатика и геоинформационные системы"
  page-footer: |
        © 2025, Татьяна Балтыжакова, Институт дизайна и урбанистики, Университет ИТМО
  navbar:
    left:
      - href: index.qmd
        text: Лекции
      - href: exam.qmd
        text: Экзамен
      - sidebar:practice
      
    right: 
      - href: https://t.me/geomess
        icon: telegram
      - icon: github
        href: https://github.com/baltti/gis-masters-course   
      
  sidebar:
    - id: practice
      title: "Практикум"
      style: "docked"
      collapse-level: 2
      contents:
        - start.qmd
      
    
  
    
            

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
lang: ru-RU    
language: custom.yml

editor: visual

