---
title: "Экзамен"
date: last-modified
date-format: "D MMMM YYYY"
number-sections: true
author:
  - affiliation: Институт дизайна и урбанистики, Университет ИТМО 
    name: Балтыжакова Татьяна
---

# Сдача экзамена

Оценка за экзамен складывается из трех составляющих:

| №   | Составляющая экзамена                                          |
|-----|----------------------------------------------------------------|
| 1   | Домашняя работа "**Подготовка карты территории исследования"** |
| 2   | Теоретическое тестирование                                     |
| 3   | Практическое задание                                           |

# Примерный перечень вопросов по теории

1.  Какой из форматов пространственных данных является мультифайловым?

2.  Что такое геоинформационная система?

3.  Когда появились первые геоинформационные системы?

4.  Как в геоинформационных системах могут использоваться растровые данные?

5.  В чем отличие растровых данных от векторных?

6.  Какой это формат векторных данных: 

```         
{

  "type": "Feature",

  "geometry": {

    "type": "Point",

    "coordinates": \[30.31, 59.94\]

  },

  "properties": {

    "name": "Санкт-Петербург"

  }

}
```

7.  В каком формате хранятся растровые данные с географической привязкой?

8.  Что такое картографическая проекция?

9.  Перечислите типы картографических проекций.

10. Какой тип картографической проекции показан на картинке?

11. Из каких компонентов состоит система координат в ГИС?

12. Какие существуют типы систем координат?

13. Основные форматы описания систем координат.

14. На каких видах тематических карт можно использовать абсолютные значения показателей?

15. На каких видах тематических карт рекомендуется использовать относительные значения показателей?

16. При каком виде классификации числовых показателей разбивка на группы происходит таким образом, чтобы между группами было максимальное отличие?

17. Какой тип тематических карт используют, если не хотят, чтобы зритель отвлекался на форму и размер объектов?

18. При каком методе классификации данных все объекты будут разделены на группы одинакового размера?

19. Можно ли при описании системы координат задать ее начало не на нулевом меридиане?

20. В чем разница между перепроецированием на лету и перепроецированием слоя?

21. Что такое проект в QGIS?

22. В чем разница между функциями \$area() и area()?

23. В чем особенность врЕменных слоев?

24. Для чего нужны макеты в QGIS?

25. Что такое векторизация?

26. Для чего необходима геопривязка растров?

27. Главная особенность геоинформационных систем.

28. Главный недостаток анаморфных карт.

29. Какие цветовые палитры могут использоваться для тематических карт?

30. Какие методы классификации могут применяться для числовых переменных?

31. Для каких переменных может быть использован тип символа Градуированный знак?

32. Для каких переменных может быть использован тип символа Уникальные значения?

33. Для чего необходимы геомодели?

34. В чем разница между инструментами “Выбрать…” и “Извлечь…”?

35. Какие типы переменных могут быть показана на тематических картах?

36. Какой период в истории ГИС называют коммерческим периодом?

37. Что относится к недостаткам формата shapefile?

38. Что такое пространственные данные?

39. Что такое пространственный объект?

40. Что такое атрибут пространственного объекта?

41. Что такое дискретные пространственные данные?

42. Что относится к непрерывным пространственным данным?

43. Что такое WMS (web map service)?

44. Какие файлы являются обязательной составляющей shapefile?

45. Формат данных GeoPackage?

46. Что такое датум?

47. На какой картинке показана нормальная/поперечная/косая проекция?

48. В каком случае необходимо назначение/присвоение системы координат?

49. В чем разница между мастабом и увеличением в окне проекта?

50. Какие типы элементов содержатся в OSM?

51. Что такое буферная зона?

# Примеры практических заданий

1.  Построить буферные зоны вокруг объектов, найти и показать на карте, какие здания попадают/не попадают в эти буферные зоны. 

2.  Рассчитать площади объектов или добавить этажность зданий (из текста в число), добавить цветовую раскраску объектов в зависимости от площади/этажности.

3.  Построить карту плотности точек по населению и оформить ее для печати.

4.  Построить картограмму по плотности населения и оформить ее для печати.

5.  Построить карту пропорциональных символов.

6.  Построить буферные зоны вокруг объектов, рассчитать количество зданий, попавших в них.
