---
title: "Домашнее задание"
number-sections: true
---

::: callout-important
Домашнее задание является вашей контрольной точкой, поэтому его выполнение обязательно!
:::

# Сбор данных

Первая часть вашей домашней работы состоит в сборе данных для "Комплексных исследований городской среды".

Каждому из вас нужно будет собрать данные о застройке и сервисах по одному или двум муниципальным образованиям (территории МО распределялись так, чтобы объём данных для сбора был примерно одинаковым).

::: callout-important
Распределение муниципальных образований приведено в таблице по ссылке <https://docs.google.com/spreadsheets/d/10aov5LvNBlUA_eG_1u5iwf4v6CWMWVsElb4zh3rHRLw/edit?usp=sharing>
:::

Что необходимо собрать:

1.  [слой 1: данные о застройке]{.underline} - все здания в муниципальном образовании в виде **полигонов**.
2.  [слой 2: данные о городских сервисах]{.underline} в виде **точечных объектов с некоторыми исключениями**. Необходимый перечень сервисов приведен в таблице по ссылке на странице *Утвержденный список сервисов* <https://docs.google.com/spreadsheets/d/10aov5LvNBlUA_eG_1u5iwf4v6CWMWVsElb4zh3rHRLw/edit?usp=sharing>

+------------------------------------+-------------------+--------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Тип объекта                        | Система координат | Тип геометрии            | Формат файла | Необходимые атрибуты                                                                                                                                                          |
+====================================+===================+==========================+==============+===============================================================================================================================================================================+
| Граница муниципального образования | WGS 84 EPSG: 4326 | Полигоны, мультиполигоны | geojson      |                                                                                                                                                                               |
+------------------------------------+-------------------+--------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Здания (жилые и не жилые)          | WGS 84 EPSG: 4326 | Полигоны, мультиполигоны | geojson      | Необходимо создать два атрибута: **«is_living», «building:levels»** — и определить тип здания (жилое оно или нежилое) и этажность.                                            |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | При создании атрибута «**is_living**» указывайте тип «*Логический*», для «**building:levels**» — «*Целое число (integer 32 бита)*».                                           |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | Порядок заполнения атрибута «**is_living**»: Жилое - 1 / истина, нежилое - 0 / ложь.                                                                                          |
+------------------------------------+-------------------+--------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Сервисы                            | WGS 84 EPSG: 4326 | Точки                    | geojson      | Необходимо указать тип сервиса в атрибуте "**service_type**", название конкретного объекта в атрибуте "**name**" (например, название школы) и его вместимость **"capacity"**. |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | Типы данных для атрибутов: "**service_type**" и "**name**" - «*Текстовый*», **"capacity" -** «*Целое число (integer 32 бита)*».                                               |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | Типы сервисов должны быть указаны также, как в таблице.                                                                                                                       |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | Вместимость заполняется только для тех сервисов, у которых это указано в таблице.                                                                                             |
+------------------------------------+-------------------+--------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Сервисы (парки и парковки)         | WGS 84 EPSG: 4326 | Полигоны, мультиполигоны | geojson      | Необходимо указать тип сервиса в атрибуте "**service_type**", название конкретного объекта в атрибуте "**name**" (например, название школы) и его вместимость **"capacity"**. |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | Типы данных для атрибутов: "**service_type**" и "**name**" - «*Текстовый*», **"capacity" -** «*Целое число (integer 32 бита)*».                                               |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | Типы сервисов должны быть указаны также, как в таблице.                                                                                                                       |
|                                    |                   |                          |              |                                                                                                                                                                               |
|                                    |                   |                          |              | Вместимость заполняется только для тех сервисов, у которых это указано в таблице.                                                                                             |
+------------------------------------+-------------------+--------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Спецификация данных

::: callout-caution
Если объект сервиса должен быть сохранен в виде точечного объекта, но в OSM обозначен только полигоном, то вам необходимо заменить полигон на его центроид.
:::

::: callout-tip
В качестве дополнительных источников данных для заполения некоторых атрибутов можете использовать:

— [ГОСВЕБ](https://gosweb.gosuslugi.ru/) — с 2026 г все бюджетные организации должны создать здесь страницы, так что это может облегчить поиск организации для уточнения вместимости;\
\
— [Я здесь живу](https://vk.ru/app7710919#kindergartens) — приложение ВК, там есть сводка занятых/свободных мест по детским садам в Петербурге.
:::

::: callout-important
Все собранные данные должны быть упакованы в архив в формате .zip.

Собранные данные необходимо загрузить по ссылке <https://disk.yandex.ru/d/MiEKgrI1YnClaA>

**Срок сдачи работы: до *1 ноября включительно***
:::

# Оформление карты

Вам нужно подготовить и оформить карту территории исследования вашего КИГС.

Порядок работы:

1.  создать новый проект;

2.  добавить подложку и собранные вами и/или вашими коллегами данные в проект (допускается использование дополнительных наборов данных при желании);

3.  задать стили вашим слоям (тут все ограничивается только вашей фантазией и художественными предпочтениями - это может быть просто выбранный вами стиль заливки или стиль, заданный на основе какого-то параметра, художественный стиль);

4.  оформить карту на макете - **обязательными элементами макета являются карта, масштабная линейка и легенда**, все остальные элементы на ваше усмотрение;

5.  экспортировать карту из макета в формат pdf или png и отправить ее в форму по ссылке.

::: callout-important
Задание можно загрузить по ссылке <https://forms.yandex.ru/u/671a67d05d2a0698658995b2>

**Срок сдачи работы: до *30 ноября включительно***
:::
