---
title: "О курсе"
date: last-modified
date-format: "D MMMM YYYY"
number-sections: false
author:
  - affiliation: Институт дизайна и урбанистики, Университет ИТМО 
    name: Балтыжакова Татьяна
brand: _brand.yml
---

## Преподаватели курса {.unnumbered}

**Балтыжакова Татьяна Игоревна**, кандидат технических наук, доцент Института дизайна и урбанистики.

**Чурякова Татьяна Алексеевна**, преподаватель Института дизайна и урбанистики.

::: callout-note
## Цитирование материалов

*Балтыжакова Т.И.* **Геоинформатика и геоинформационные системы** : сайт. 2026. — URL: <https://baltti.github.io/gis-masters-course/>. DOI: [10.5281/zenodo.19049765](https://doi.org/10.5281/zenodo.19049765)
:::

# Общие сведения

Это страница с материалами курса по дисциплине **"Геоинформатика и геоинформационные системы"**.

Основная цель дисциплины состоит в получении студентами базовых навыков работы с пространственными данными средствами геоинформационных систем. В рамках дисциплины обучающиеся ознакомятся с историей геоинформационных систем, основными форматами пространственных данных и базовыми методами их анализа, а также подходами к визуализации пространственных данных.

Материалы состоят из лекций, в который преимущественно представлены общие понятия геоинформатики, и практикума, в котором рассмотрены работа в настольной геоинформационной системе [QGIS](https://qgis.org/).

# Промежуточная аттестация по курсу

В конце курса вас ожидает **экзамен**.

Оценка за экзамен складывается из трех составляющих:

| №   | Составляющая экзамена      |
|-----|----------------------------|
| 1   | Домашняя работа            |
| 2   | Теоретическое тестирование |
| 3   | Практическое задание       |

::: callout-important
Выполнение домашней работы является обязательным.

Те, кто не ее не сдадут, не будут допущены к экзамену.
:::

Перечень вопросов и примерных заданий будет опубликован позднее.

::: callout-tip
## Обратная связь

Если вы заметили ошибку или опечатку, можете написать мне на почту tibaltyzhakova\@itmo.ru или оставить [issue](https://github.com/baltti/gis-masters-course/issues) в репозитории курса на GitHub.
:::
